export const cols = [
  {
    field: "id",
    headerName: "ID",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "age",
    headerName: "Age",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "registerId",
    headerName: "Register ID",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "zipCode",
    headerName: "ZipCode",
    align: "center",
    headerAlign: "center",
  },
];

export const rows = [
  {
    id: 1,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 2,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 3,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 4,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 5,
    name: "Asmaa Hassan",
    email: "hoda@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 6,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 7,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 8,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 9,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
  {
    id: 10,
    name: "Asmaa Hassan",
    email: "asmaa14has@gmail.com",
    age: 30,
    phone: "01056789923",
    address: "xcvt sdfsd vdgd",
    city: "cairo",
    zipCode: "10001",
    registerId: 12351,
  },
];
